### PR TITLE
lauren's updated intro, trouble merging

### PR DESCRIPTION
**Pull request by laurenrhuang**
I don't think I did this correctly, Github is telling me I can't automatically merge this pull request and the same message when I try to fetch upstream? I'm not too sure where I should go to fix the conflicts

### CODE REVIEW

**Comment by JasonFreeberg** [comment]
Hey @laurenrhuang are you free on Sunday? I'm meeting with Eiton so we can talk for 20 min after that

**Comment by JasonFreeberg** [comment]
I see the problem you're having, I can explain it on paint

**Comment by laurenrhuang** [comment]
@JasonFreeberg yes i am free! what time are you thinking of?

**Comment by laurenrhuang** [comment]
hi @JasonFreeberg I got the email, 6:30 works for me!

**Review by JasonFreeberg — APPROVED** [review]

**Pull request merged**
